AllCops:
  Exclude:
    - Guardfile

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/HashSyntax:
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - ruby19_no_mixed_keys
    - hash_rockets
# Force hashes that have a symbol value to use hash rockets
  UseHashRocketsWithSymbolValues: true
